/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "vending_machine_constants.h"

namespace vending_machine {

const vending_machineConstants g_vending_machine_constants;

vending_machineConstants::vending_machineConstants() {
}

} // namespace

