/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef vending_machine_CONSTANTS_H
#define vending_machine_CONSTANTS_H

#include "vending_machine_types.h"

namespace vending_machine {

class vending_machineConstants {
 public:
  vending_machineConstants();

};

extern const vending_machineConstants g_vending_machine_constants;

} // namespace

#endif
